name: Deploy Web Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY_PEM }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Setup Web Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        # Update system and install nginx
        sudo yum update -y
        sudo yum install nginx -y
        
        # Start nginx service
        sudo systemctl start nginx
        sudo systemctl enable nginx

        # Open firewall for HTTP
        sudo firewall-cmd --zone=public --add-port=80/tcp --permanent
        sudo firewall-cmd --reload
        
        # Setup simple web page
        echo "<h1>Welcome to my website</h1>" | sudo tee /usr/share/nginx/html/index.html

        # Restart nginx
        sudo systemctl restart nginx
        EOF

    - name: Verify Deployment
      run: |
        curl http://${{ secrets.EC2_HOST }}
